export { default as LoginForm } from "./LoginForm/LoginForm";
export { default as RegisterForm } from "./RegisterForm/RegisterForm";
export { default as Loader } from "./Loader/Loader";
export { default as NavBar } from "./NavBar/NavBar";
export { default as CreditCard } from "./CreditCard/CreditCard";
export { default as UpdateForm } from "./UpdateForm/UpdateForm";
export { default as Timer } from "./Timer/Timer";
export { default as Alert } from "./PopUps/Alert/Alert";
export { default as Confirm } from "./PopUps/Confirm/Confirm";
